server:
  port: 31000
  
spring:
  rabbitmq:
    host: t_m_rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: t_m_DB
      host: t.m.mongo
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://t_m_infra_discovery-server:18761/eureka/

logging:
  level:
    ROOT: INFO
