server:
  port: 41000
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: complexs
      host: localhost
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/
  instance:
    hostname: localhost
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
 
logging:
  level:
    ROOT: INFO
