server:
  port: 31000
  
spring:
  rabbitmq:
    host: t.m.rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: complexs
      host: t.m.mongo
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://t.m.infra.discovery-server:18761/eureka/

logging:
  level:
    ROOT: INFO
