server:
  port: 41000
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: complexs
      host: localhost
  sleuth:
    annotation:
      enabled: true
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/
 
logging:
  level:
    ROOT: INFO
