server:
  port: 28888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/
 
logging:
  level:
    ROOT: INFO
    
spring:
  cloud:
    gateway:
      routes:
      - id: set_request_host_header_route
        uri: http://localhost:28888/headers
        predicates:
        - Path=/headers
        filters:
        - name: SetRequestHost
          args:
            host: localhost:41000
