server:
  port: 41300
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  sleuth:
    annotation:
      enabled: true
    
  data:
    mongodb:
      database: t_m_DB
      host: localhost
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/
      
person:
  service: PERSON
  oauth:
    client_id: 442cf4015509eda9c03e5ca3aceef752
    client_secret: 4f7ec648a48b9d3fa239b497f7b6b4d8019697bd

logging:
  level:
    ROOT: WARN
