server:
  port: 41100
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  sleuth:
    annotation:
      enabled: true
    
  data:
    mongodb:
      database: t_m_DB
      host: localhost
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
 
logging:
  level:
    ROOT: WARN

